name = "splitter"
version = "1.1.0"
description = "Efficiently slice prefixes from strings. Good for parsers!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "splitter" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
